"""[shim] 구현은 c2.domain.wargame.terrain 로 이동됨 (KoreaRealTerrain 및 관련 상수)."""
from c2.domain.wargame.terrain import (  # noqa: F401
    KoreaRealTerrain,
    REF_LAT,
    REF_LON,
    MAP_W_M,
    MAP_H_M,
    GRID_RES,
    GRID_W,
    GRID_H,
    METERS_PER_DEG_LAT,
    METERS_PER_DEG_LON,
    ZOOM,
    TX_MIN,
    TX_MAX,
    TY_MIN,
    TY_MAX,
    DATA_DIR,
    DEM_FILE,
    META_FILE,
)
